spring:
  application:
    name: payment-processing
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/estore_payments
    username: ${DB_USERNAME:estore}
    password: ${DB_PASSWORD:estore}
  sql:
    init:
      mode: always

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.estore: DEBUG
    org.springframework: INFO
