-- User Management Service: Users and profiles
-- Run after 01-create-schema.sql

SET search_path TO user_management;

-- Enum types
DO $$ BEGIN
    CREATE TYPE user_status AS ENUM ('active', 'inactive', 'suspended', 'pending_verification');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE auth_provider AS ENUM ('local', 'google', 'facebook', 'apple');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Users (authentication credentials)
CREATE TABLE IF NOT EXISTS users (
    id                  BIGSERIAL       PRIMARY KEY,
    email               VARCHAR(255)    NOT NULL UNIQUE,
    email_verified      BOOLEAN         NOT NULL DEFAULT FALSE,
    email_verified_at   TIMESTAMPTZ,
    password_hash       VARCHAR(255),                       -- NULL when using OAuth only
    auth_provider       auth_provider   NOT NULL DEFAULT 'local',
    provider_user_id    VARCHAR(255),                       -- OAuth provider's user ID
    status              user_status     NOT NULL DEFAULT 'pending_verification',
    failed_login_count  SMALLINT        NOT NULL DEFAULT 0,
    locked_until        TIMESTAMPTZ,
    last_login_at       TIMESTAMPTZ,
    last_login_ip       INET,
    password_changed_at TIMESTAMPTZ,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- Refresh tokens for JWT authentication
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id              BIGSERIAL       PRIMARY KEY,
    user_id         BIGINT          NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash      VARCHAR(255)    NOT NULL UNIQUE,
    device_info     VARCHAR(500),
    expires_at      TIMESTAMPTZ     NOT NULL,
    revoked_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- User profiles (personal information)
CREATE TABLE IF NOT EXISTS user_profiles (
    user_id         BIGINT          PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    first_name      VARCHAR(100)    NOT NULL,
    last_name       VARCHAR(100)    NOT NULL,
    display_name    VARCHAR(150),
    date_of_birth   DATE,
    gender          VARCHAR(20),
    phone_number    VARCHAR(30),
    phone_verified  BOOLEAN         NOT NULL DEFAULT FALSE,
    avatar_url      VARCHAR(2048),
    bio             TEXT,
    locale          VARCHAR(10)     NOT NULL DEFAULT 'en-US',
    timezone        VARCHAR(50)     NOT NULL DEFAULT 'UTC',
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- User preferences and settings
CREATE TABLE IF NOT EXISTS user_preferences (
    user_id                 BIGINT      PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    email_notifications     BOOLEAN     NOT NULL DEFAULT TRUE,
    sms_notifications       BOOLEAN     NOT NULL DEFAULT FALSE,
    push_notifications      BOOLEAN     NOT NULL DEFAULT TRUE,
    marketing_emails        BOOLEAN     NOT NULL DEFAULT FALSE,
    order_updates           BOOLEAN     NOT NULL DEFAULT TRUE,
    newsletter              BOOLEAN     NOT NULL DEFAULT FALSE,
    currency                CHAR(3)     NOT NULL DEFAULT 'USD',
    language                VARCHAR(10) NOT NULL DEFAULT 'en',
    theme                   VARCHAR(20) NOT NULL DEFAULT 'light',
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Seed example admin user.
-- IMPORTANT: password_hash MUST be replaced with a real bcrypt hash (cost factor >= 12)
-- generated by your application before use. The placeholder below is intentionally
-- invalid — the account cannot be logged into until a valid hash is set.
-- Example (Node.js):  bcrypt.hashSync('YourSecurePassword!', 12)
-- Example (Python):   bcrypt.hashpw(b'YourSecurePassword!', bcrypt.gensalt(rounds=12))
INSERT INTO users (email, email_verified, email_verified_at, password_hash, status)
VALUES ('admin@estore.local', TRUE, NOW(), 'PLACEHOLDER_REPLACE_WITH_BCRYPT_HASH', 'active')
ON CONFLICT (email) DO NOTHING;
